workflows:
  ios-workflow:
    name: iOS Workflow
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS release
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release archive -archivePath $CM_BUILD_DIR/build/App.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/build
    artifacts:
     - ios/build/*.ipa
